env:
  browser: true
  commonjs: true
  es2021: true
  mocha: true
extends:
  - airbnb-base
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
rules: {}
